name: Redmine Ultimate Pack 한국어판
description: |
  Redmine 기반의 올인원 프로젝트 관리 솔루션입니다. AI 도우미, 애자일 칸반 보드, 
  고급 간트 차트, GitLab 연동, 이슈 템플릿, 태그 시스템 등 10여 개의 필수 플러그인이 
  사전 설치되어 즉시 사용 가능합니다. 한국어 UI에서 '일감' 용어를 '이슈'로 변경하여 
  국내 환경에 최적화되었으며, 모던한 Opale 테마를 포함한 다양한 테마가 제공됩니다.

instructions: |
  기본 관리자 계정: admin/admin
  - 한국어 UI 적용 ('일감' → '이슈' 변경)
  - AI 도우미는 관리 > 플러그인에서 API 키 설정 필요
  - 기본 테마: Opale 적용
  - 프로젝트별로 플러그인 모듈 활성화 필요

changeLog:
  - date: 2024-10-28
    description: 기본 템플릿 추가
  - date: 2025-02-28
    description: 버전 6.0.3으로 업데이트
  - date: 2025-07-24
    description: 버전 6.0.6으로 업데이트
  - date: 2025-01-15
    description: Ultimate Pack 플러그인 및 한국어 최적화 적용

links:
  - label: Website
    url: https://www.redmine.org/
  - label: Documentation
    url: https://www.redmine.org/guide
  - label: Github
    url: https://github.com/redmine/redmine
contributors:
  - name: Ahson Shaikh
    url: https://github.com/Ahson-Shaikh
schema:
  type: object
  required:
    - appServiceName
    - databaseServiceName
    - appServiceImage
  properties:
    appServiceName:
      type: string
      title: App Service Name
      default: redmine
    appServiceImage:
      type: string
      title: App Service Image
      default: redmine:6.0.6
    databaseServiceName:
      type: string
      title: Database Service Name
      default: redmine-db
benefits:
  - title: 즉시 사용 가능한 고급 기능
    description: |
      AI 도우미, 애자일 칸반 보드, WBS, 고급 간트 차트, 인라인 편집기 등 
      프리미엄 플러그인들이 사전 설치되어 배포 즉시 활용 가능합니다.
  - title: 개발팀 친화적 워크플로우
    description: |
      GitLab 웹훅 연동으로 커밋과 이슈를 자동 연결하고, 멘션 기능과 태그 시스템으로 
      효율적인 협업 환경을 제공합니다.
  - title: 한국어 환경 최적화
    description: |
      UI의 '일감' 용어를 '이슈'로 변경하여 국내 개발 환경에 맞게 최적화하였으며, 
      다양한 모던 테마로 사용자 경험을 향상시켰습니다.

features:
  - title: AI 기반 이슈 관리
    description: |
      AI 도우미가 긴 이슈 내용을 요약하고, 코드를 설명하며, 하위 작업을 제안하여 
      프로젝트 관리 효율성을 극대화합니다.
  - title: 애자일 칸반 보드
    description: |
      드래그 앤 드롭으로 이슈를 쉽게 관리할 수 있는 시각적 칸반 보드와 
      애자일 워크플로우를 지원합니다.
  - title: 고급 간트 차트 및 WBS
    description: |
      프로페셔널한 WBS(작업분해구조)와 인터랙티브 간트 차트로 
      프로젝트 일정을 체계적으로 관리할 수 있습니다.
  - title: 실시간 협업 기능
    description: |
      인라인 이슈 편집, @멘션 기능, 태그 시스템으로 팀원 간 실시간 소통과 
      협업이 원활하게 이루어집니다.
  - title: GitLab 완전 통합
    description: |
      GitLab 웹훅을 통해 커밋 메시지로 이슈를 자동 업데이트하고 
      코드 변경 사항을 실시간으로 추적할 수 있습니다.
  - title: To-do 리스트 및 이슈 템플릿
    description: |
      체크리스트 기능과 이슈 템플릿으로 일관된 업무 프로세스를 구축하고 
      작업 진행 상황을 세밀하게 관리할 수 있습니다.

tags:
  - 프로젝트 관리
  - 이슈 추적
  - 애자일
  - 칸반
  - AI 도우미
  - GitLab 연동
  - 한국어
  - 협업 도구
