# meta.yaml

# 템플릿의 고유 이름 (URL 등에 사용)
name: redmine-ultimate-pack-kr

# 템플릿 목록에 표시될 제목과 설명
description: |
  최신 Redmine을 기반으로 Agile, Gantt, GitLab 연동, AI 도우미 등 10종 이상의 필수 플러그인과 
  모던 테마를 사전 설치한 올인원(All-in-One) 프로젝트 관리 솔루션입니다. 
  한국어 환경에 맞춰 UI의 '일감' 용어를 '이슈'로 변경하여 팀의 직관적인 사용을 돕습니다.

# 설치 후 사용자에게 보여줄 안내사항
instructions: |
  - Default admin login: admin/admin
  - 기본 테마로 'Opale'이 적용되어 있으며, 한국어 UI의 '일감'이 '이슈'로 변경되었습니다.
  - AI Helper 플러그인은 관리 > 플러그인 > 설정에서 API 키를 입력해야 동작합니다.

# 템플릿 변경 이력
changeLog:
  - date: 2025-08-28 # 현재 날짜나 작업 날짜를 기입하세요.
    description: >-
      Ultimate Pack template created with 10+ plugins, 3 themes, 
      and Korean language customization.

# 관련 외부 링크 (Redmine 공식 사이트)
links:
  - label: Website
    url: https://www.redmine.org/
  - label: Documentation
    url: https://www.redmine.org/guide
  - label: Github
    url: https://github.com/redmine/redmine

# 배포 시 사용자에게 보여줄 입력 폼 정의
schema:
  type: object
  required:
    - appServiceName
    - databaseServiceName
    - appServiceImage
  properties:
    appServiceName:
      type: string
      title: App Service Name
      default: redmine-ultimate
    appServiceImage:
      type: string
      title: App Service Image
      # ✅ 중요: 이 부분을 당신이 빌드해서 푸시한 Docker 이미지 주소로 변경해야 합니다.
      default: your-dockerhub-username/redmine-ultimate-pack:latest
    databaseServiceName:
      type: string
      title: Database Service Name
      default: redmine-db

# 이 템플릿 사용 시 얻을 수 있는 핵심 혜택
benefits:
  - title: 즉시 사용 가능한 고급 워크플로우
    description: >-
      애자일 보드, 고급 간트 차트, 이슈 템플릿이 사전 설치되어 있어, 배포 즉시 
      최신 방법론에 기반한 프로젝트 관리를 시작할 수 있습니다.
  - title: 개발 및 AI 연동 자동화
    description: >-
      GitLab 연동으로 코드와 이슈 추적을 자동화하고, AI 도우미가 이슈 요약 및 질문 답변을 
      지원하여 팀의 생산성을 극대화합니다.
  - title: 완벽한 한글화 및 맞춤 UI
    description: >-
      모든 플러그인이 현대적인 'Opale' 테마와 통합되었으며, 한국어 UI를 '이슈' 중심으로 
      개선하여 명확하고 직관적인 사용자 경험을 제공합니다.

# 이 템플릿에 포함된 주요 기능
features:
  - title: 애자일 칸반 보드 (Agile & Kanban Boards)
    description: >-
      Redmine Agile 플러그인을 통해 Trello처럼 직관적인 드래그 앤 드롭 방식으로 
      작업 현황을 시각적으로 관리할 수 있습니다.
  - title: AI 어시턴트 (AI Assistant)
    description: >-
      AI Helper 플러그인이 긴 이슈를 요약하고, 코드에 대해 설명하며, 
      하위 작업을 제안하는 등 지능적인 지원을 제공합니다.
  - title: GitLab 연동 (GitLab Integration)
    description: >-
      GitLab Hook 플러그인을 통해 커밋 메시지로 이슈를 자동으로 연결하거나 
      종료(close)할 수 있어 개발 워크플로우가 간소화됩니다.
  - title: 고급 간트 차트 (Advanced Gantt Charts)
    description: >-
      Easy Gantt 플러그인이 내장되어, 드래그 앤 드롭으로 프로젝트 일정을 손쉽게 
      수립하고 종속성을 관리할 수 있습니다.
  - title: 워크플로우 자동화 (Workflow Automation)
    description: >-
      Automation 플러그인을 사용하여 '이슈 생성 시 담당자 자동 할당' 등 
      반복적인 작업을 자동화하는 규칙을 만들 수 있습니다.

# 템플릿 검색을 위한 태그
tags:
  - Project Management
  - Issue Tracking
  - Agile
  - Kanban
  - GitLab
  - DevOps
  - AI